spring:
  config:
    activate:
      on-profile: "qa"

build:
  version : "2.0"

accounts:
  message: "Welcome to LokeshIndustries accounts related QA APIs -external "
  contactDetails:
    name: "Arun Sundar - QA Lead"
    email: "arun@lokeshindustries.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345